name: smpl_clothing_website
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  line_awesome_flutter: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - web/images/brand/logo.png
    - web/images/brand/shirts_overview_background.png
    - web/images/shirts/shirt_0.png
    - web/images/shirts/shirt_1.png
    - web/images/shirts/shirt_2.png
    - web/images/shirts/shirt_3.png
    - web/images/shirts/shirt_4.png
    - web/images/shirts/shirt_5.png
    - web/images/arrows/down_arrow_yellow.png
    - web/images/arrows/right_arrow_yellow.png
    - web/images/arrows/left_arrow_yellow.png
    - web/images/arrows/down_arrow_black.png
    - web/images/arrows/up_arrow_black.png
    - web/images/arrows/right_arrow_black.png
    - web/images/arrows/left_arrow_black.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Louis George Cafe
      fonts:
        - asset: web/fonts/louis_george_cafe/Louis George Cafe Light.ttf
          weight: 300
        - asset: web/fonts/louis_george_cafe/Louis George Cafe Light Italic.ttf
          weight: 300
          style: italic
        - asset: web/fonts/louis_george_cafe/Louis George Cafe.ttf
        - asset: web/fonts/louis_george_cafe/Louis George Cafe Italic.ttf
          style: italic
        - asset: web/fonts/louis_george_cafe/Louis George Cafe Bold.ttf
          weight: 700
        - asset: web/fonts/louis_george_cafe/Louis George Cafe Bold Italic.ttf
          weight: 700
          style: italic
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
